### PR TITLE
Assorted fixes for code rot

### PR DESCRIPTION
**Pull request by mgorny**
Here's a combined effort to update the package after all the code rot. So far I've focused on fixing running the test suite via `tox` and now I'm working on fixing compatibility with newer versions of packages. It's partially my work and partially stuff taken from existing PRs.

Technically it's a work-in-progress but I'm doing things atomically, so it's fine to merge it at any point, and I'll just rebase.

### CODE REVIEW

**Comment by mgorny** [comment]
Ok, that accounts for all the patches we've had in Gentoo, and gives me a clean test pass with newest versions of `Flask`, `werkzeug` and the bunch, and up to Python 3.12.

**Comment by kevin1024** [comment]
Thanks for your work on this @mgorny.

Could you take a look at the test failure on windows?  Not sure what that's all about.

**Comment by mgorny** [comment]
Thanks. I'll try to take a look in a few minutes, just when I'm done with my immediate TODO.

**Comment by mgorny** [comment]
> Could you take a look at the test failure on windows? Not sure what that's all about.

It seems that the problem is that `rpds-py` fails to build on PyPy3.9 on Windows, apparently with some "cancelled" error. I don't really know what it's about, it could be a problem with PyO3 or the GitHub environment. Unfortunately, I'm not a Rust expert, so I don't really know what to do about it. I'd suggest just excluding that test environment from the test matrix.

**Pull request merged**
